### ISSUE TITLE
HOME - Tamaño y animación del banner principal

### ISSUE THREAD

**Issue by julianapina** [daringh/goliquidator#10]
El referente para el banner principal es el de este demo: https://suprema.select-themes.com/

- Debe tener un alto como el de ese referente (en mi pantalla, que es de 1920 x 1080, px) veo el alto del banner de 500px... 650px sería un buen alto -tomando como referencia mi pantalla-).

- El comportamiento debe ser como el del referente (animaciones).

_Mira, el del referente es un banner que ocupa gran parte de la pantalla, pero no el 100%. Abajo se alcanzan a ver otros elementos; sin embargo, no es tan pequeño como el que hay ahora_
![banner ref](https://user-images.githubusercontent.com/56084137/66351024-638f3400-e922-11e9-8cdf-24db5b5d28cd.PNG)

-------

**IMPORTANTE:** ten en cuenta que este banner debe ser construido pensando en que habrá otra versión para los dispositivos XS y XXS, con una imagen cuadrada (posiblemente de 1024 x 1024). En este momento está hecho con Slider Revolution (tengo entendido que nos funciona para este fin, pero no estoy segura).

**Comment by daringh** [comment]
no se entiende muy bien, podrias especificar mejor a q te refieres

**Comment by julianapina** [comment]
@daringh  Revisa please el banner de este link: https://suprema.select-themes.com/ (es el original del template).

Me gustaría que el alto del banner principal sea como el de este. Actualmente está mucho menor al del referente.

No podría decirte con exactitud cuántos pixels de alto debe tener porque veo que es variable según el tamaño de la pantalla. Yo tengo un monitor de 1920 x 1080, y específicamente para esta resolución queda muy bien de unos 650px.

Lo que me gustaría es que revises el referente del link y le apliques el mismo alto y las mismas animaciones.

Hazme saber si me explico bien :)

**Comment by julianapina** [comment]
@daringh  El bloque de texto no estaba bien centrado respecto al alto del banner, pero yo ya lo moví. Para que tengas presente que hice ese cambio :).
