### ISSUE TITLE
HOME - Banner vídeo

### ISSUE THREAD

**Issue by julianapina** [daringh/goliquidator#12]
No siempre nos quedaremos con el mismo texto, a veces podríamos poner alguno de mayor extensión, así que hay que hacer algunos ajustes:

Font-size: 38px
Line-height: 50px
Padding: 12.5% 15% 12.5% 15%

- Poner el alfa del background negro en 0.7 → rgba(10,10,10,0.7)

![banner video](https://user-images.githubusercontent.com/56084137/66279742-e5c31e00-e878-11e9-9791-3e195a57b6c0.PNG)

**Comment by daringh** [comment]
cual de los textos

**Comment by daringh** [comment]
me podrias adjuntar una imagen

**Comment by julianapina** [comment]
@daringh ¡Ya está!

**Comment by julianapina** [comment]
@daringh Perdóname la vida, pero ya no lo vi lindo con el texto tan pequeño (sorry jaja). Ponlo por fa de 43px.
