### ISSUE TITLE
HOME - Banner "Cómo comprar"

### ISSUE THREAD

**Issue by julianapina** [daringh/goliquidator#14]
- **Tamaño del texto principal (título):**

Font-size: 72px
Line-heignt: 75px

![cómo comprar - título](https://user-images.githubusercontent.com/56084137/66216013-4c361980-e68a-11e9-8985-333f34159085.PNG)

------------

- **Botón**

Cambiar color para el estado hover por: #171f37

---------

**IMPORTANTE:** Este banner y el de abajo también deben tener una versión especial para dispositivos XS y XXS, por lo que es necesario revisar si la manera en la que están construidos nos funciona para ese propósito.

**Comment by daringh** [comment]
la imagen no queda bien con el diseño 
![Screen Shot 2019-10-06 at 9 34 19 PM](https://user-images.githubusercontent.com/5013983/66279730-3d658780-e881-11e9-828d-e8c0e6fb79b5.png)

**Comment by daringh** [comment]
quieres q cambie la columna

**Comment by julianapina** [comment]
@daringh Gary sorry, aquí me equivoqué. Esta imagen es para el banner "Nuestro catálogo". Voy a mover ese ajuste al "issue" al que corresponde.
