### ISSUE TITLE
HOME - Testimonios

### ISSUE THREAD

**Issue by julianapina** [daringh/goliquidator#16]
- Limitar en desktop el ancho total del bloque de testimonios a 1200 px para que no se extienda por toda la pantalla.

-------

- Faltan estas flechas para desplazar los testimonios (sé que por ahora hay solo 3, pero si pongo un testimonio adicional tampoco aparecen)

![testimonios](https://user-images.githubusercontent.com/56084137/66217823-9b317e00-e68d-11e9-8df8-653435c3f3e8.PNG)

--------

- Poner el país debajo del nombre de la persona, como si fuera el nombre de la compañía (en gris #777777 a 13px)

![testimonios- país](https://user-images.githubusercontent.com/56084137/66217914-c5833b80-e68d-11e9-9564-1d6b9cafd813.PNG)

**Comment by daringh** [comment]
no se puede poner el pais

**Comment by julianapina** [comment]
@daringh Mira como está en el template original. Debería poderse ¿no?: https://suprema.select-themes.com/testimonials/

![testimonials](https://user-images.githubusercontent.com/56084137/66317349-f6a67a80-e8de-11e9-869a-542652559ae2.PNG)

**Comment by julianapina** [comment]
@daringh , en este faltan dos cositas:

1. Limitar el ancho total del bloque a unos 1200 px para que estos testimonios no se extiendan por todo el ancho de la pantalla.

2. Que parezcan las flechas para desplazar cuando hayan más de 3 testimonios

La idea es que se ve más como esto:

![testimonios](https://user-images.githubusercontent.com/56084137/66417569-e3220f00-e9c5-11e9-9001-8a756b1d5ab5.PNG)
