### ISSUE TITLE
CATÁLOGO - Tabla de excel

### ISSUE THREAD

**Issue by julianapina** [daringh/goliquidator#18]
Tabla actual: https://drive.google.com/drive/u/1/folders/1aaTO8G42MFHGDpzYegnX7JlAkFohifpe

**Hacer las correcciones necesarias a la tabla para el ingreso de producto masivo (agregar/quita/modificar los campos que necesites). Para esta tabla es necesario tener en cuenta lo siguiente:**

------------

**Campo para Nombre del producto**
Tanto en la grilla como en la página de producto aparece el nombre de cada artículo.

--------------

**Campo para Descripción corta**
En la grilla, cada producto tiene una descripción corta de unos 80 caracteres

![GRILLA](https://user-images.githubusercontent.com/56084137/66426471-84fe2780-e9d7-11e9-8db3-18e742fdca1b.PNG)

----------

**Campo para SKU**
En la página de producto aparece el SKU para cada artículo.

----------

**Dos campos para la información del producto**
La información de cada artículo va a estar dividida en dos en la página de producto, así que es necesario crear dos campos (uno para cada uno de estos bloques de información).

![DESCRIPCIONES](https://user-images.githubusercontent.com/56084137/66427434-87618100-e9d9-11e9-9b97-c2b03aa62fae.PNG)

--------------

**Un campo dinámico en el que se pueda introducir manualmente el precio o info de contacto**
No todos los productos tienen un precio fijo. La idea es que no sea un campo limitado al precio, sino que se pueda escribir cualquier cosa con una extensión corta, por ejemplo:
- Llame al (1) 786-615-6677
- Desde 5 USD
- 800 USD
- etc

![precio](https://user-images.githubusercontent.com/56084137/66428377-8a5d7100-e9db-11e9-880f-a16ab3843563.PNG)

------------

**Imágenes de producto**
Es necesario tener en cuenta que cada producto tiene varias fotos:

- Una foto principal
- Unas fotos secundarias.

No sé si se requieren varios campos, o si se separan las URLs por comas en un mismo campo.

------------

**Categorías del producto**
Cada producto está asignado como mínimo a una categoría y una sub-categoría, pero pueden haber productos que se asignen a varias.

En la tabla original, sebastián determinó que la categoría y sub-categoría se asignarían así:
Categoría madre > Categoría hijo

Y si pertenece a varias se separarían por comas, por ejemplo:
Ropa > Masculina, Ropa > Marcas famosas

Revisa las diapositivas 20, 21 y 22 de este documento para un mayor entendimiento de lo que intento explicar:
[Guía formato de excel - Importación productos.pptx](https://github.com/daringh/goliquidator/files/3704478/Guia.formato.de.excel.-.Importacion.productos.pptx)

**Importante:** Debes tener en cuenta que las categorías principales de producto no son cliqueables, es decir, lo único que hacen es desplegar las sub-categorías. Sin embargo, para cada categoría principal existirá una sub-categoría llamada "Ver todo" en la que sí saldrán todos los productos asociados esa categoría principal. Para que me entiendas mejor, revisa las notas en color azul de la página 1 de este documento: https://docs.google.com/document/d/1BchIJfF-BzrVFuEPhct3XqHShKmX-ALc77ANuh1ndRE/edit

------------------

**Campo "published"**
Con valor 1 o 0. Para determinar si el producto queda publicado automáticamente cuando se suba, o si se publica luego a través de Wordpress manualmente.

---

**Otras consideraciones**
No es necesario hacer referencia al stock, ya que no se va a mostrar y como no tenemos carrito de compras tampoco es relevante.

**Comment by daringh** [comment]
[wc-product-import-final.zip](https://github.com/daringh/goliquidator/files/3778567/wc-product-import-final.zip)

**Comment by julianapina** [comment]
@daringh, ¿crees que podemos manejar cada dato en una columna diferente del Excel? A Ire le da un "yeyo" donde yo le diga que toda la información general del producto se pone en una sola celda. ¿Se puede manejar de la siguiente manera?:

Col A: Type
Col B: SKU
Col C: Name
Col D: subtitle
Col E: Published
Col F: Is featured?
Col G: Visibility in catalog
Col H: Short description
Col I: Description
Col J: In stock?
Col K: Sold individually?
Col L: Allow customer reviews?
Col M: Sale price
Col N: Regular price
Col O: alternativo_al_precio
Col P: Categories
Col Q: Tags
Col R: Images
Col S: Position
