### ISSUE TITLE
CERTIFICADO SSL

### ISSUE THREAD

**Issue by julianapina** [daringh/goliquidator#19]
Se supone que el certificado SSL está activado y es válido, pero sale esta alerta:

![ssl](https://user-images.githubusercontent.com/56084137/66431964-ad3f5380-e9e2-11e9-824b-7b2cbb347d8a.jpg)

Es indispensable que las personas no queden con dudas. Necesitamos que el sitio se perciba como 100% seguro.

**Comment by daringh** [comment]
se verifico si los ssl estan activos
se modificaron las urls para q sean https en el panel administrador
se busco en la base de datos direcciones http://developer.goliquidator.com que estaban en el entorno de produccion
se actualizaron las imagenes que se subieron como http
se busco en el codigo direcciones http para remplazarlos por https

![ssl1](https://user-images.githubusercontent.com/5013983/66538472-7bb5ad80-eaf2-11e9-9fad-40a0b368430e.png)
![ssl2](https://user-images.githubusercontent.com/5013983/66538474-7bb5ad80-eaf2-11e9-8f3a-d3da22cd2530.png)
![ssl3](https://user-images.githubusercontent.com/5013983/66538475-7bb5ad80-eaf2-11e9-9012-2cf993e0da0c.png)

**Comment by daringh** [comment]
se instalo certificado gratuito para develop
![2019-10-10_0103](https://user-images.githubusercontent.com/5013983/66540476-f0401a80-eaf9-11e9-8219-9cef1c3a94f7.png)
![2019-10-10_01042](https://user-images.githubusercontent.com/5013983/66540477-f0401a80-eaf9-11e9-8bd8-04a28633545e.png)
