### ISSUE TITLE
REVIEWS DE GOOGLE

### ISSUE THREAD

**Issue by julianapina** [daringh/goliquidator#25]
Poner visibles los reviews de Google en el sitio (ubicarlo en el lado izquierdo de la página).

![image (17)](https://user-images.githubusercontent.com/56084137/68442169-2c6ca680-019e-11ea-8ea3-daedc1fd4a9b.png)

**Comment by daringh** [comment]
![2019-11-17_1924](https://user-images.githubusercontent.com/5013983/69015964-f387bb00-096f-11ea-80a4-7fcc7f0ea919.png)
ya esta instaldo

**Comment by julianapina** [comment]
Gracias @daringh, voy a decirle a Ire que cree el "API Key" para revisarlo.
