### ISSUE TITLE
FOOTER - Suscripción al boletín de noticias

### ISSUE THREAD

**Issue by julianapina** [daringh/goliquidator#9]
Falta la opción para suscribirse al boletín de noticias en la cuarta columna. Hasta ahora se tenía previsto que fuera un botón que lleve a la URL del formulario de suscripción a modo de modal o pop-up, pero si existe una mejor alternativa para vincular Constant Contact con Mailchimp estoy abierta a las posibilidades (y avísame si necesitas acceso a Constant Contact)

El estado hover de este botón puede ser con fondo blanco y letra negra.

![boletín](https://user-images.githubusercontent.com/56084137/66214644-b39e9a00-e687-11e9-8ce9-d3e9cdd78492.PNG)

**Formulario de suscripción de Constant Contact:**
https://visitor.r20.constantcontact.com/manage/optin?v=001jYqn93s1IRBAjuOk0kLpaUjoTG3ZuUW3yNeJcD7a1fttY6owOSkDst3Tr4Oyfw_gKpZjt17sr5f88jBXpaIVfqUYQ_6GFtg3VQlf9EYeLyc%3D

**Nota:** si necesitas acceso a Constant Contact me cuentas.

**Comment by daringh** [comment]
ready for review

**Comment by julianapina** [comment]
@daringh ¿Es posible aumentar un poco el ancho de esta columna? Así podríamos hacer lo siguiente:

- Dejar el texto "Copyright 2019..." en una sola línea

**Para el botón:**

- padding: 13px 20px;
- font-size: 13px;
- margin-bottom: unos 15 o 20 px (dejar espacio entre el botón y los métodos de pago)

**Comment by daringh** [comment]
se lo dejo como 
padding: 12px 7px;
font-size: 12px;
margin-bottom: 20px;
width: 100%;

**Comment by julianapina** [comment]
@daringh me gusta, pero aún lo siento muy "apeñuscado" y con la fuente muy pequeña. Hagamos lo siguiente:

- Cambiemos el texto por "Suscríbase para recibir ofertas" ...Quitar la palabra "nuestras".

- Si es posible, poner el font size a 13 px.
